# Generated by Django 3.0.7 on 2020-11-26 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('title', helpers.models.NotNullNotBlankCharField(max_length=50)),
                ('content', helpers.models.NotNullNotBlankCharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'topic')},
            },
        ),
    ]
